name: Promote
on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  promote:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'merge_group' && (github.event.workflow_run.event == 'push' || github.event.workflow_run.event == 'workflow_dispatch')
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/promote@v1
        with:
          project-type: maven
